config/routes.rb
Rails.application.routes.draw do
  root to: 'ponies#index'

  resources :ponies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pony.rb
class Pony < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ponies_controller.rb
class PoniesController < ApplicationController
  before_action :set_pony, only: [:show, :edit, :update, :destroy]

  # GET /ponies
  def index
    @ponies = Pony.all
  end

  # GET /ponies/1
  def show
  end

  # GET /ponies/new
  def new
    @pony = Pony.new
  end

  # GET /ponies/1/edit
  def edit
  end

  # POST /ponies
  def create
    @pony = Pony.new(pony_params)

    if @pony.save
      redirect_to @pony, notice: 'Pony was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /ponies/1
  def update
    if @pony.update(pony_params)
      redirect_to @pony, notice: 'Pony was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /ponies/1
  def destroy
    @pony.destroy
    redirect_to ponies_url, notice: 'Pony was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pony
      @pony = Pony.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def pony_params
      params.require(:pony).permit(:name, :description, :color)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ponies_helper.rb
module PoniesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PeachHeart</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/ponies/_form.html.erb
<%= form_for(pony) do |f| %>
  <% if pony.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pony.errors.count, "error") %> prohibited this pony from being saved:</h2>

      <ul>
      <% pony.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :color %>
    <%= f.text_field :color %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ponies/edit.html.erb
<h1>Editing Pony</h1>

<%= render 'form', pony: @pony %>

<%= link_to 'Show', @pony %> |
<%= link_to 'Back', ponies_path %>

app/views/ponies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ponies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ponies.each do |pony| %>
      <tr>
        <td><%= pony.name %></td>
        <td><%= pony.description %></td>
        <td><%= pony.color %></td>
        <td><%= link_to 'Show', pony %></td>
        <td><%= link_to 'Edit', edit_pony_path(pony) %></td>
        <td><%= link_to 'Destroy', pony, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pony', new_pony_path %>

app/views/ponies/new.html.erb
<h1>New Pony</h1>

<%= render 'form', pony: @pony %>

<%= link_to 'Back', ponies_path %>

app/views/ponies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pony.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pony.description %>
</p>

<p>
  <strong>Color:</strong>
  <%= @pony.color %>
</p>

<%= link_to 'Edit', edit_pony_path(@pony) %> |
<%= link_to 'Back', ponies_path %>